FROM golang:1.21.1-alpine3.18 as builder

WORKDIR /usr/app

COPY . .

RUN go mod init hello && \
  go build

FROM scratch
WORKDIR /exec
COPY --from=builder /usr/app/hello .
ENTRYPOINT [ "/exec/hello" ]